version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_DB
    environment:
      POSTGRES_DB: clinicDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: clinic_app
    environment:
      DB_CONN_STR: ${DB_CONN_STR}
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./pkg/infra/migrations/sql:/app/sql

  nginx:
    image: nginx:alpine
    container_name: clinic_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: